image: node:latest

stages:
  - lint

eslint:
  stage: lint
  script:
    # Install ESLint in this docker container
    - npm install --silent eslint eslint-plugin-html eslint-plugin-import eslint-plugin-vue
    # Run ESLint
    - ./node_modules/.bin/eslint --ext .js,.vue src
