sudo: required
dist: trusty
language: node_js
matrix:
  include:
  - os: osx
    osx_image: xcode8.3
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+\-?[a-z]*$/
node_js:
- '8'
install:
- npm install
script:
- printf "CLIENT_SECRET=$CLIENT_SECRET\nNODE_ENV=production" > .env
- npm run build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: rU1Y9lKjqH7wtgr04qdSTNrfKRVUxu4zYjTvPa6pNp6NTRwAuPBqwQRWEZQg/tHoY+Jh6to1q8QW4fzQ6prz4r7gOrbKtHn+t6p8SlZ7H3KAi3kek2CRF3dKR/TDXVbWaFCOhewQ5eoEOz7JvNlNcM+Lq3QG3VxkPZrek3ZDAsMdiZddoxvBfaxSAQA/CLKupOD5wpw30gufTTaRaA0SIFeDTU74q2j661UOyySYaAf1XFnFwRa9DS0Wtg4zmZoL4Ib9R6y8Pr3RVoHGFVyG5pWuBFCbx8VxAX0B37iv1/w7ce9pnVdw2jrkxxzzxGUNxlOfr+SLX3UarZ1py+cBGMDXZUi9FnhW9dhdjgHQHhpgGhE4npUbJ2LYcIbSzFM/aeMFsrNGPDXlPARHNiCcc0t1xH7ypjoHYDRpvHz/JLq7v4rmyqGWapOz1H4Y5gnD6MkMML05siRpA6Xh5k0iCaAApzPUv6+vZOzsobK4Ww8M0bGNiQzST5XY/yHG2Ioo7GXr+HV8CTYGkpJndMldqANyr/LVrl2Tke1TSeSYnd5E/ObSNXQ2g/0RGS/tS3CgrWg+bCKcksEw5td+YaXDdz1u+eMFxEFNjhk3/jZrlhcx4l/2WPm1HeMBsqWYUBdXK2vn41P+DVfSyhx+voKGQsmNc+iXkICyb5vKCyZD6VQ=
  file_glob: true
  file:
  - build/*.deb
  - build/*.dmg
  - build/*.snap
  - build/*.tar.gz
  prerelease: true
  draft: false
  tag_name: "$TRAVIS_TAG"
  name: ZeroTwo $TRAVIS_TAG
  on:
    tags: true
    repo: NicoAiko/zerotwo
