sudo: required
dist: trusty
language: node_js
matrix:
  include:
  - os: osx
    osx_image: xcode8.3
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
    - "node_modules"
node_js:
  - "8"
install:
  - npm install
script:
  - npm run build:clean
  - travis_wait 30 npm run build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: JgTBr84/mPhTUAA8rHIGVN750hV2m/HnSSwuGxYHlKzt6NrhLXU28w7efjEfN6X6zpjrW00FWqrELFx/MqaHqvOJ8WE4fB4CVvXYCAclDClcv7ZgVf0DPHarImXjUe5clQ3ssFAhvHrtDarjVvXtSefot2iMevujbEIE7rtvRQijMPJvzXbO2KsR19fZw+XiJIKSNRdXPmlFKJukTpMlGZLj9yzAppffbr0g8zf3YlyFKeod6O5yQ4kT5v3LFLJTFtAro83DxIU0+uQWw7fedjpeb4Fb2RtV07WucXCJrfkZDI8Qsa7MRwR94SaJBKD0yaIWUDgg43yHgZo5tInBdpz9Yl7L0JerpiZhmVk+utk1ON0fA6AixKVBtX/yRpxpDZob/utVxmGH76EjiWpxaeJOqZLdEhllIgAKEB4Rhoh26LTNdk0TnV3PSXlSIL53HpDGiIineG+pcl6Bs0R+akNqwSnpv2H3gvH6MA+MzwAhRRwyrQvtrjgcfhK3TKrfxSn9nC/+lWKYODQvMVUOdjjEJw9wkFlfYFODuOuLMKNRn4gIXZf0of4JCrNmQcY4sV4v/fn8QbCj988jM7IIswBMs6gAkhDhZHLwbv2JZ0hPwS6WS4Yv/kxpeJLZMlZ46zTQMvBJ7SpXeLWQeS7o2f8Cv80XMkhVY1J7CAmBpZI=
  file_glob: true
  file:
    - "build/*.AppImage"
    - "build/*.deb"
    - "build/*.snap"
    - "build/*.dmg"
  on:
    repo: NicoAiko/zerotwo
branches:
  only:
  - master
after_success:
  - sh set_tags.sh
