sudo: required
dist: trusty
language: node_js
matrix:
  include:
  - os: osx
    osx_image: xcode8.3
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
node_js:
- '8'
install:
- npm install
script:
- npm run build:clean
- travis_wait 30 npm run build
deploy:
  prerelease: true
  draft: false
  tag_name: "$TRAVIS_TAG"
  name: ZeroTwo $TRAVIS_TAG
  provider: releases
  api_key:
    secure: "mSNq58RSWS2i+vOVp5GC7TEqzF68F6ZVQjxrYZSW3Fj4P3OjyVrTBhJgN/vzd6MajghcPBd6twORO4xhId9YoTNXbC+56gqA3GjhxcgoC5+fjt5D98dfgoXnw74esDg3T122dDtDtSet/Uem/QtxNZ/C7P/bOgAy6b/xCjxBZxpkqV3SbG51c85VCg+WIQzFjzm4xyyKmo8GcMlarZuOG5+rXnljgw74KzUdwKZxvJUIx/3a9SSpOb6GoIlnY+RW70pA9Rl5imU/WC6AZF4iIzJyUt7tlfQarRu/bfjSpwbY2Dalp6Gfew7lhMhl821BidM3X7W0rGursK0cAauTk2UN8N34QwsG0mgGRQVmI8vY+JZlP67lrjOG2NsDw6wLMouaduWv8P6xgMVspryer5Q227/AoxdeO0vfSqHFL2zgKe1qnBZqRTxSl3BZXcdD7JYbV4l0+rVLqBvfiM9DtZwo/f8Dy8aiy/l/ES1veADxRbz9cQg6nl2QWCu7gcmDOy8iyGlQyaCsKUX0iZdZWq97rrhJmNJ7rZ4ixfsep/nBSUijr2jfQ1+4ARcnKrPRWwYCyLgUnIOBOAtaUjd4vq+9/K5wXZPk5ePG9ArrrK+uxVr7qwLth4zfquMi1xR2VDpsQjzuAYVawptYg3e30PutsCNJV1CpMVMSDUbB528="
  file_glob: true
  file:
  - build/*.deb
  - build/*.dmg
  on:
    repo: NicoAiko/zerotwo
    tags: true
branches:
  only:
  - "/v\\d+\\.\\d+\\.\\d+\\-?[a-z]*/"
