branches:
  only:
    - master

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%/npm-cache'
  - '%USERPROFILE%/.electron'

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run build:clean
  - npm run build

test: off

deploy:
  provider: GitHub
  prerelease: true
  draft: true
  force_update: true
  repository: NicoAiko/zerotwo
  description: ''
  release: $(appveyor_repo_tag_name)
  artifact: build\*.exe
  auth_token:
    secure: 2l9QA3INcc7ZP0Ye2bV5n7cNfi7WpRb2AjX1nSV878So7aX/K8+a+kFwqMWtUsLS
  on:
    branch: master
    appveyor_repo_tag: true
