branches:
  only:
  - master

platform: Any CPU

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8
  - npm install

environment:
  CLIENT_SECRET:
    secure: JMBmvZNgm2X7uTsEe1b7sPKoJHSqowjcHxDZ+/vdzGixlY7ycTrYC1Igf9hKQz8U
  github_token:
    secure: diMKIMZOOqW72A72qO+L0ybzXp1TC8GpG/YdFc6Oi7o/098qezYRnKPDpNkUYF+M

before_build:
  - ps: $env:NODE_ENV="production"
  - ps: echo "CLIENT_SECRET=$env:CLIENT_SECRET`r`nNODE_ENV=production" > .env

build_script:
  - npm run build

test: off

artifacts:
- path: 'build\*.exe'

skip_non_tags: true

deploy:
  provider: GitHub
  prerelease: true
  force_update: true
  repository: NicoAiko/zerotwo
  description: ''
  tag: $(appveyor_repo_tag_name)
  release: ZeroTwo $(appveyor_repo_tag_name)
  auth_token: $(github_token)
  on:
    branch: master
    appveyor_repo_tag: true
