branches:
  only:
    - master

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%/npm-cache'
  - '%USERPROFILE%/.electron'

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run build:clean
  - npm run build

test: off

deploy:
  provider: GitHub
  prerelease: true
  force_update: true
  repository: NicoAiko/zerotwo
  description: ''
  release: ZeroTwo-v0.$(appveyor_build_version)
  artifacts:
    - path: "build\\*.exe"
      name: '*.exe'
      type: File
  auth_token:
    secure: 7YWkBvHOxRb7TmxwBrOYd2c20Ht86u6aNq9TbZfMeLxcdAqVg2P6V0ZRvPmqyLIs
  on:
    branch: master
