branches:
  only:
  - master

platform:
  - x64

init:
  - git config --global core.autocrlf input

cache:
  - node_modules
  - '%APPDATA%/npm-cache'
  - '%USERPROFILE%/.electron'

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run build:clean
  - npm run build

test: off

artifacts:
- path: 'build\*.exe'

skip_non_tags: true

deploy:
  provider: GitHub
  prerelease: true
  force_update: true
  repository: NicoAiko/zerotwo
  description: ''
  tag: $(appveyor_repo_tag_name)
  release: ZeroTwo $(appveyor_repo_tag_name)
  auth_token:
    secure: 2l9QA3INcc7ZP0Ye2bV5n7cNfi7WpRb2AjX1nSV878So7aX/K8+a+kFwqMWtUsLS
  on:
    branch: master
    appveyor_repo_tag: true
